version: '3.3'
services:
  wine-eccomerce:
    container_name: wine-eccomerce
    command: npm run serve
    env_file:
      - .env
    tty: true
    working_dir: /app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '${DOCKER_SERVER_PORT}:8080'
